########################################################################
#                       Rust Style Configuration                       #
#                                                                      #
# This file controls the operation of `rustfmt` and `cargo fmt`. As    #
# the `rustfmt` tool still has many unstable options, this file        #
# contains only the configuration options that are stable when it was  #
# last touched.                                                        #
#                                                                      #
# See <https://rust-lang.github.io/rustfmt/?version=v1.4.37>           #
########################################################################

# array_width = 60                   # Leave implicit
# attr_fn_like_width = 70            # Leave implicit
# chain_width = 60                   # Leave implicit
edition = "2018"
fn_args_layout = "Tall"
# fn_call_width = 60                 # Leave implicit
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Never"
max_width = 81
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
# single_line_if_else_max_width = 50 # Leave implicit
# struct_lit_width = 18              # Leave implicit
# struct_variant_width = 35          # Leave implicit
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
